import com.lund.Indexer;
import org.junit.Before;
import org.junit.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Kristian' at '10.02.16 15:22' with Gradle 2.2.1
 *
 * @author Kristian, @date 10.02.16 15:22
 */
public class IndexerTest {

    Indexer indexer;
    
    @Before
    public void setup() {
        indexer = new Indexer();    
    }

    @Test public void testThatCorectNumberOfWordsAreFoundByIndexLine() {
        Map<String, Integer> indexMap = indexer.indexLine("A short line.", new HashMap<>());
        assertEquals(3, indexMap.size());
    }

    @Test public void testThatWordsAreLowerCasedByIndexLine() {
        Map<String, Integer> indexMap = indexer.indexLine("A short line.", new HashMap<>());
        assertTrue(indexMap.containsKey("a"));
        assertFalse(indexMap.containsKey("A"));
    }

    @Test public void testThatOnlyAToZIsIndexedByIndexLine() {
        Map<String, Integer> indexMap = indexer.indexLine("A short line.", new HashMap<>());
        assertTrue(indexMap.containsKey("line"));
        assertFalse(indexMap.containsKey("line."));
    }

    @Test public void testThatCorrectCountIndexedByIndexLine() {
        Map<String, Integer> indexMap = indexer.indexLine("A short short line.", new HashMap<>());
        assertTrue(indexMap.get("line") == 1);
        assertTrue(indexMap.get("short") == 2);
    }
}
